# default config
observers-must-ready: true

# how long players can be absent
absence-time-seconds: 120

api:
  enabled: false
  url: https://localhost:3000/v1/
  key: authorisation-key
  getMatch: /match/{server}
  matchResults: /match/{server}/finish
  playerAbandon: users/{uuid}/invalidate