# default config

# how long players can be absent
absence-time-seconds: 120

# match will auto end if players missing
full-teams-required: true

# enable the requeue command and prompt
allow-requeue: true

# enable the forfeit command and prompt
forfeit:
  enabled: true
  after: "300s"

# duration to countdown before starting match
match-start-duration: "300s"

# website page links (remove section to remove references)
web:
  match: https://localhost:3000/matches/{matchId}
  profile: https://localhost:3000/{name}

# api connection details
api:
  url: https://localhost:3000/v1/
  key: authorisation-key

